### PR TITLE
Add Code of Conduct Page

### PR DESCRIPTION
**Pull request by ecarlisle**
This enhancement is [issue 2](https://github.com/charmCityJs/charmcityjs.github.io/issues/2).  Additional related changes were added. Hopefully these weren't too out of scope, but a lot of them aren't cosmetic changes.  Also, apologize for the initial huge commit. :-P  
Changes include:
1. Code of Conduct from CharmCityJS MeetUp site added as /code-of-conduct.html.  All links on site point to local Code of Conduct document.
2. Web page and telephone links added on Code of Conduct except for 911.
3. Link to code of conduct added and consolidated with other links into a top navigation.
4. Top navigation uses Flexbox CSS properties for mobile-first presentation.  Media query added so until 768px pixel width, navigation is vertical.  At 768px and above, navigation is vertical.  Flexbox vendor prefixes have been added for cross-browser support.  
5. Semantic tags added to for `<header>`,`<nav>`, `<main>`, `<footer>`, and `<section>`.  "Our Sponsors" section is being used for `<footer>`.
6. "Our Sponsors" section has same Flexbox mobile-first behaviors as navigation (vertical until 768px).
7. `<footer>` has same width as `<nav>` for visual balance (seen by horizontal line).
8. Add home hyperlink to logo.
9. Remove markup elements that are used for padding / margins.  Place respective cosmetics in CSS.
10. All images using a CSS class to be responsive.

**Notes:** 
1. [This issue](https://github.com/charmCityJs/charmcityjs.github.io/issues/2) offered _BIG SUPER BONUS POINTS_ for using [The MeetUp API](http://www.meetup.com/meetup_api/) so that the Code of Contact changes need only be maintained in one location.  I was unable to find API functionality to do this.
2. Neither of the URLs for Taxi Cab Companies point to a working site.  I'll verified this on Google.  I'll add an issue for this.

### CODE REVIEW

**Comment by jasonrhodes** [comment]
I'm ... so confused! I swore I left a comment on this a few days ago asking for a few final changes to get it merged but when I come back now I don't see my comment and I see a ton more changes... don't have time to review the new ones before I leave for a week so if someone else wants to take a look, go for it.

**Comment by esauter5** [comment]
@jasonrhodes I found it. You put your comments in the corresponding issue: https://github.com/charmCityJs/charmcityjs.github.io/issues/2#issuecomment-235138714

**Comment by esauter5** [comment]
@ecarlisle Code looks good to me. I'll try to take a look at the actual pages tomorrow and then assuming you incorporated @jasonrhodes comments, we should be able to get this merged.

**Comment by ecarlisle** [comment]
@jasonrhodes - Sorry again for the scope creep.  I'll keep everything on the field next time. 

@esauter5 - Thanks for helping!  I believe I did take note of the comments addressed in the commit notes.  What I added that was out of scope was placing static assets in a main /assets/ folder (and changing all affected links).

Thanks!
Eric

**Comment by ecarlisle** [comment]
@jasonrhodes , @esauter5 :
Bump? :-)

**Pull request merged**
